### PR TITLE
fixed bug in sync.sh, updated script

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Regular repository has been used for `shadow-fixed` images as well.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
Nobody complained (or cared ;)) -> please merge

**Comment by gavanderhoorn** [comment]
@AustinDeric also +1-ed this, so I guess he's ok with it.

I can merge it, but it's not my repository. @AustinDeric ?

**Comment by 130s** [comment]
+1

**Comment by AustinDeric** [comment]
@gavanderhoorn sorry i totally missed this, please feel free to merge in the future.  Its "our" repository.

Thanks!

**Pull request merged**
