### PR TITLE
Add Noetic Support for Tesseract and Noether

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Do you know how to update the docker hub so it includes the newly added docker builds?

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn Do you know how to update the docker hub so it includes the newly added docker builds?

No, not without looking at the docs myself I'm afraid.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: did you add the new SSH key for Docker Hub integration?

**Comment by mathias-luedtke** [comment]
> Do you know how to update the docker hub so it includes the newly added docker builds?

We have setup automated builds, they do not always run after a push..
In this case, they can be triggered by anyone, who is a member of the team on Docker Hub.

**Comment by Levi-Armstrong** [comment]
> @Levi-Armstrong: did you add the new SSH key for Docker Hub integration?

I don't believe so. I just created the tesseract repository on docker hub and to support build args I had to add the build hook for it to work. This was the same for noether.

**Comment by Levi-Armstrong** [comment]
> We have setup automated builds, they do not always run after a push..
In this case, they can be triggered by anyone, who is a member of the team on Docker Hub.

Thank you. To solve the issue I had to create a new repository on Docker Hub for each docker added to the repository. Once I created the repository for Tesseract they are now getting built.

**Pull request merged**
