### PR TITLE
Added travis config

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Distributed over different jobs in topological order.

I am not sure about the caffe fixes.
The project's Dockerfile seem to be broken as well (https://github.com/BVLC/caffe/issues/6374).

Please activate Travis for this repository.

### CODE REVIEW

**Comment by 130s** [comment]
> Please activate Travis for this repository.

I second this. It'll allow reviewers to see more easily what this PR does.

**Comment by AustinDeric** [comment]
@ipa-mdl **Awesome work thanks!** I went ahead and tested this and it works: https://travis-ci.org/AustinDeric/docker/builds/383435066

A few housekeeping things:
 - lets see if this merge triggers an automated build as per #14 
 - I am going to add the travis badge in an upcoming PR  (@Levi-Armstrong please turn travis on for this repo.)
 - next time, please [squash the commits](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit), 4 is a little excessive for this PR.

**Comment by mathias-luedtke** [comment]
> next time, please squash the commits, 4 is a little excessive for this PR.

IMHO the commits should document the process and help the reviewer to understand what's going on.
For example 7c5b60aeb74b796a0b94a13e95c88274b91e0a91 migth be solved by specifying the most recent version instead.

Feel free to squash-merge ;)

**Review by AustinDeric — APPROVED** [review]

**Comment by AustinDeric** [comment]
Great Point! Again, Great work as well!  I am going to merge because this looks great to me.

**Pull request merged**
