### PR TITLE
Add caffe &  nvidia-docker support

### PR DESCRIPTION
**Pull request by AustinDeric**
I pushed images to the docker repository so they can be evaluated:

https://hub.docker.com/r/rosindustrial/ros-core-nvidia/
https://hub.docker.com/r/rosindustrial/ros-base-nvidia/
https://hub.docker.com/r/rosindustrial/ros-robot-nvidia/
https://hub.docker.com/r/rosindustrial/core-nvidia/
https://hub.docker.com/r/rosindustrial/caffe-gpu/

This will help with our artificial intelligence and deformable material efforts.  Does anyone have any ideas for naming conventions?  Right now i am changing the image name for different layers and keeping the tag strictly related to ROS releases.

Thanks,
-Austin

### CODE REVIEW

**Comment by AustinDeric** [comment]
I am going to merge this soon.  If anyone wants to review this, please let me know shortly.

**Comment by mathias-luedtke** [comment]
I am not sure about the license..

**Comment by AustinDeric** [comment]
Thanks! I just created a commit to remove the license

**Comment by AustinDeric** [comment]
I am going to merge this. if there are any issues then please create an issue and i will take care of it asap.

Thank you again,

**Pull request merged**
